version: '3.8'

services:
  backend:
    image: medicare-backend
    container_name: medicare_backend
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/medicare
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=Qwerty6@
    ports:
      - "8080:8080"
    depends_on:
      - mysql

  frontend:
    image: medicare-frontend
    container_name: medicare_frontend
    ports:
      - "80:80"

  mysql:
    image: mysql:8
    container_name: medicare_mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: medicare
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
